[package]
name = "nameful-cli"
version = "1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.29.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
toml = "0.9.8"
xdg = "3.0.0"
